name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  PROJECT_PATH: './src/Penzle.Core.csproj/bin/Release'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_PUSH_URL: ${{ secrets.NUGET_PUSH_URL }}
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Test
        run: dotnet build --configuration Release --no-restore && dotnet test --no-restore --verbosity normal

      - name: Semantic Release
        uses: actions/semantic-release@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          debug: true

      - name: Publish to NuGet
        uses: nuget/publish@1.0.0
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-packages-directory: ${{ env.PROJECT_PATH }}
          nuget-package-version: ${{ steps.semantic_release.outputs.next_version }}
          nuget-package-id: Penzle.Net
