name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  PROJECT_PATH: 'src/Penzle.Core.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_PUSH_URL: ${{ secrets.NUGET_PUSH_URL }}
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Setup Node.js
      uses: actions/setup-node@v2.5.2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install semantic-release
      run: npm ci
      working-directory: ./

    - name: Semantic Release
      id: semantic
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: ${{ env.PROJECT_PATH }}
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        PACKAGE_NAME: 'Penzle.Net'
        VERSION: ${{ steps.semantic.outputs.new_release_version }}
