# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Action For Semantic Release
      uses: cycjimmy/semantic-release-action@v3.4.2
      with:
       branches: main
    - name: Install NuGet CLI
      run: |
        dotnet tool install -g NuGet.CommandLine
      shell: bash
    - name: Pack NuGet package
      run: |
        dotnet pack --no-build --configuration Release --include-symbols --include-source
      shell: bash
    - name: Publish to NuGet
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
      run: |
        nuget push ./bin/Release/*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json
      shell: bash
    
