name: Publish to NuGet

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Build with dotnet
      run: dotnet build --configuration Release QueryVortex.Core/QueryVortex.Core.csproj

    - name: Get Version
      id: version
      uses: battila7/get-version-action@v2

    - name: Pack project
      run: dotnet pack QueryVortex.Core/QueryVortex.Core.csproj --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ./

    - name: Push package
      run: |
        dotnet nuget push "*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
