name: Trigger auto deployment for png-production-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/png-production-container-app-AutoDeployTrigger-d12fd6dd-a1e7-4796-83d7-9bc09f53c018.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: pnzdemocontainerregistry.azurecr.io
          username: ${{ secrets.PNGPRODUCTIONCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.PNGPRODUCTIONCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pnzdemocontainerregistry.azurecr.io/pnz-api-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PNGPRODUCTIONCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n png-production-container-app -g pnz-production-app-rg --server pnzdemocontainerregistry.azurecr.io --username  ${{ secrets.PNGPRODUCTIONCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.PNGPRODUCTIONCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n png-production-container-app -g pnz-production-app-rg --image pnzdemocontainerregistry.azurecr.io/pnz-api-app:${{ github.sha }}
